### ISSUE TITLE
[FEAT] chat GPT 연동

### ISSUE THREAD

**Issue by ParkJunGyu26** [ParkJunGyu26/capstone-middleware#1]
## 💡 Feature Issue
- chat gpt api를 roblox studio와 연동할 수 있도록 합니다.
- GET method로 테스트 해본 이후, roblox studio에서 post 형식으로 프롬프트를 작성할 수 있도록 구현합니다.

## 🌿 To-do
- [ ] 미들웨어(nestJS)에 chat gpt api 연동 확인(api-key)
- [ ] (로컬 서버) GET 방식으로 roblox studio에서 gpt 호출 확인
- [ ] (로컬 서버) POST 방식으로 roblox studio에서 gpt 호출 확인
