### ISSUE TITLE
[FEAT] 월드 간 score 공유

### ISSUE THREAD

**Issue by ParkJunGyu26** [ParkJunGyu26/capstone-middleware#9]
## 💡 Feature Issue
Earth, Space 서로 다른 월드에서 '점수'에 대해 공유하기 위한 api입니다.

## 🌿 To-do
- [x] Prisma(ORM) 설정
- [x] 점수 저장 api
- [x] 점수 조회 api
- [ ] 데이터베이스 마이그레이션(mongodb -> mysql)
- [ ] 소요 시간 저장 api
